export const appStyles: Record<string, React.CSSProperties> = {
  app: {
    display: 'flex',
    width: '100vw',
    height: '100vh',
    overflow: 'hidden',
    background: '#1e1e1e',
  },
  left: {
    width: '50%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
  },
  right: {
    width: '50%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
  },
}

export const codeEditorStyles: Record<string, React.CSSProperties> = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    borderRight: '1px solid #333',
  },
  header: {
    padding: '8px 12px',
    background: '#1e1e1e',
    color: '#ccc',
    fontSize: 12,
    fontWeight: 600,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    borderBottom: '1px solid #333',
  },
}

export const visualEditorStyles: Record<string, React.CSSProperties> = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    background: '#1e1e1e',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '8px 12px',
    background: '#252526',
    color: '#ccc',
    fontSize: 12,
    fontWeight: 600,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    borderBottom: '1px solid #333',
  },
  statusBar: {
    fontFamily: 'monospace',
    fontSize: 13,
    color: '#4fc1ff',
    background: '#1e1e1e',
    padding: '4px 8px',
    borderRadius: 4,
  },
  addBtn: {
    padding: '4px 12px',
    background: '#007acc',
    border: 'none',
    borderRadius: 4,
    color: '#fff',
    fontSize: 12,
    cursor: 'pointer',
  },
  canvas: {
    flex: 1,
    position: 'relative',
    overflow: 'hidden',
    background: '#f5f5f5',
  },
  iframe: {
    width: '100%',
    height: '100%',
    border: 'none',
  },
}

export const propertyPanelStyles: Record<string, React.CSSProperties> = {
  overlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: 'rgba(0, 0, 0, 0.6)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
  },
  modal: {
    background: '#252526',
    borderRadius: 8,
    padding: 20,
    width: 400,
    maxHeight: '80vh',
    overflow: 'auto',
    boxShadow: '0 8px 32px rgba(0, 0, 0, 0.4)',
  },
  title: {
    marginBottom: 20,
    color: '#ccc',
    fontSize: 14,
  },
  attrList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
    marginBottom: 20,
  },
  field: {
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
  },
  label: {
    color: '#999',
    fontSize: 12,
    textTransform: 'uppercase',
  },
  input: {
    padding: '8px 12px',
    background: '#3c3c3c',
    border: '1px solid #555',
    borderRadius: 4,
    color: '#fff',
    fontSize: 14,
    fontFamily: 'monospace',
  },
  actions: {
    display: 'flex',
    gap: 12,
    justifyContent: 'flex-end',
  },
  cancelBtn: {
    padding: '8px 16px',
    background: 'transparent',
    border: '1px solid #555',
    borderRadius: 4,
    color: '#ccc',
    cursor: 'pointer',
  },
  confirmBtn: {
    padding: '8px 16px',
    background: '#007acc',
    border: 'none',
    borderRadius: 4,
    color: '#fff',
    cursor: 'pointer',
  },
}

export const positionPickerStyles: Record<string, React.CSSProperties> = {
  overlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: 'rgba(0, 0, 0, 0.6)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
  },
  modal: {
    background: '#252526',
    borderRadius: 8,
    padding: 20,
    width: 360,
    boxShadow: '0 8px 32px rgba(0, 0, 0, 0.4)',
  },
  title: {
    marginBottom: 20,
    color: '#ccc',
    fontSize: 14,
  },
  field: {
    marginBottom: 16,
  },
  label: {
    display: 'block',
    marginBottom: 8,
    color: '#999',
    fontSize: 12,
    textTransform: 'uppercase',
  },
  select: {
    width: '100%',
    padding: '8px 12px',
    background: '#3c3c3c',
    border: '1px solid #555',
    borderRadius: 4,
    color: '#fff',
    fontSize: 14,
  },
  edgeGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, 1fr)',
    gap: 8,
  },
  edgeBtn: {
    padding: '10px',
    background: '#3c3c3c',
    border: '1px solid #555',
    borderRadius: 4,
    color: '#ccc',
    cursor: 'pointer',
    fontSize: 13,
  },
  edgeBtnActive: {
    background: '#007acc',
    borderColor: '#007acc',
    color: '#fff',
  },
  input: {
    width: '100%',
    padding: '8px 12px',
    background: '#3c3c3c',
    border: '1px solid #555',
    borderRadius: 4,
    color: '#fff',
    fontSize: 14,
  },
  preview: {
    padding: '12px',
    background: '#1e1e1e',
    borderRadius: 4,
    marginBottom: 16,
    textAlign: 'center',
  },
  actions: {
    display: 'flex',
    gap: 12,
    justifyContent: 'flex-end',
  },
  cancelBtn: {
    padding: '8px 16px',
    background: 'transparent',
    border: '1px solid #555',
    borderRadius: 4,
    color: '#ccc',
    cursor: 'pointer',
  },
  confirmBtn: {
    padding: '8px 16px',
    background: '#007acc',
    border: 'none',
    borderRadius: 4,
    color: '#fff',
    cursor: 'pointer',
  },
}